a.out: mission1.o mission2.o mission3.o mission4.o mission5.o ex3.o
	gcc mission1.o mission2.o mission3.o mission4.o mission5.o ex3.o

task1.o: mission1.c mission1.h
	gcc -c mission1.c
 
task2.o: mission2.c task2.h 
	gcc -c mission2.c
 
task3.o: mission3.c mission3.h
	gcc -c mission3.c
 
task4.o: mission4.c mission4.h
	gcc -c mission4.c

task5.o: mission5.c mission5.h
	gcc -c mission5.c
 
ex3.o: ex3.c
	gcc -c ex3.c
 

